export default [
  { type: 'canvas', id: 'equipment', detail: {modelName:'equipment'} },
  { type: 'tabgroup', parentId: 'equipment', id: 'equipment_tabgroup1', detail: { isMain:true }},
  { type: 'tab', parentId: 'equipment_tabgroup1', id: 'equipment_tabgroup1_tab1', detail: { label: '列表',type:'list'}},
  { type: 'table', parentId: 'equipment_tabgroup1_tab1', id: 'equipment_tabgroup1_tab1_table1',
    detail: { label: '',isMain: true,width:1400,bordered:false }},
  { type: 'tablecol', parentId: 'equipment_tabgroup1_tab1_table1', id: 'equipment_tabgroup1_tab1_table1_col1',
    detail: { label: '装备编号',dataAttribute:'eqNum',event:'selectRecord',width: 400}},
  { type: 'tablecol', parentId: 'equipment_tabgroup1_tab1_table1', id: 'equipment_tabgroup1_tab1_table1_col2',
    detail: { label: '装备描述',dataAttribute:'desc',width: 400}},
  { type: 'tablecol', parentId: 'equipment_tabgroup1_tab1_table1', id: 'equipment_tabgroup1_tab1_table1_col4',
    detail: { label: '创建时间',dataAttribute:'created_time',width: 400}},
  { type: 'tablecol', parentId: 'equipment_tabgroup1_tab1_table1', id: 'equipment_tabgroup1_tab1_table1_col5',
    detail: { label: '状态',dataAttribute:'status',width: 400}},
  { type: 'tablecol', parentId: 'equipment_tabgroup1_tab1_table1', id: 'equipment_tabgroup1_tab1_table1_col6',
    detail: { label: '书签',width:60,event:'bookmark',eventValue:'eqNum',align:'center'}},
  { type: 'tab', parentId: 'equipment_tabgroup1', id: 'equipment_tabgroup1_tab2', detail: { label: '详情',type:'insert'}},
  { type: 'sectionrow', parentId: 'equipment_tabgroup1_tab2', id: 'equipment_tabgroup1_tab2_row1', detail: {}},
  { type: 'sectioncol', parentId: 'equipment_tabgroup1_tab2_row1', id: 'equipment_tabgroup1_tab2_row1_col1', detail: {}},
  { type: 'sectioncol', parentId: 'equipment_tabgroup1_tab2_row1', id: 'equipment_tabgroup1_tab2_row1_col2', detail: {}},
  { type: 'sectioncol', parentId: 'equipment_tabgroup1_tab2_row1', id: 'equipment_tabgroup1_tab2_row1_col3', detail: {}},
  { type: 'multiparttextbox', parentId: 'equipment_tabgroup1_tab2_row1_col1', id: 'equipment_tabgroup1_tab2_row1_col1_text1',
    detail: {label:'装备编号',dataAttribute: 'eqNum', descDataAttribute: 'desc', descInputMode: 'readonly',lookup: 'selectEQ1', lookupKeyMap: [['eqNum','desc'],['eqNum','desc']]}},
  { type: 'multilinetextbox', parentId: 'equipment_tabgroup1_tab2_row1_col1', id: 'equipment_tabgroup1_tab2_row1_col1_text2',
    detail: {label:'装备描述',dataAttribute: 'desc',rows:4}},

  { type: 'textbox', parentId: 'equipment_tabgroup1_tab2_row1_col2', id: 'equipment_tabgroup1_tab2_row1_col2_text1',
    detail: {label:'关联物料',dataAttribute: 'item.itemNum', lookup: 'selectItem', menuType:'WO', lookupKeyMap: [['itemNum'],['itemNum']]}},
  { type: 'textbox', parentId: 'equipment_tabgroup1_tab2_row1_col3', id: 'equipment_tabgroup1_tab2_row1_col2_text2',
    detail: {label:'创建日期',dataAttribute: 'created_time', dataType: 'datetime'}},

  { type: 'section', parentId: 'equipment_tabgroup1_tab2', id: 'equipment_tabgroup1_tab2_section1', detail: {}},
  { type: 'table', parentId: 'equipment_tabgroup1_tab2_section1', id: 'equipment_tabgroup1_tab2_section1_table1',
    detail: { label: '关联人员',objName: 'assocPerson',pageSize: 5}},
  { type: 'tablecol', parentId: 'equipment_tabgroup1_tab2_section1_table1', id: 'equipment_tabgroup1_tab2_table1_col1',
    detail: { label: '人员编号',dataAttribute:'personID'}},
  { type: 'tablecol', parentId: 'equipment_tabgroup1_tab2_section1_table1', id: 'equipment_tabgroup1_tab2_table1_col2',
    detail: { label: '人员名称',dataAttribute:'name'}},
  { type: 'tablecol', parentId: 'equipment_tabgroup1_tab2_section1_table1', id: 'equipment_tabgroup1_tab2_table1_col3',
    detail: { label: '邮箱',dataAttribute:'email'}},
]
