export default [

  { type: 'dialog', id: 'status', detail: { label: '变更状态', width: 400,}},
  { type: 'combobox', parentId: 'status', id: 'status_combo1',
    detail: {label:'新状态',dataAttribute: 'status', inputMode:'required',keyAttribute: 'value', displayAttribute: 'description', listAttribute: 'statusSelect', span: 18}},
  { type: 'pushbutton', parentId: 'status', id: 'bookmark_btn1', detail: { label: '确定',isDefault: true, event: 'changeStatus' }},
  { type: 'pushbutton', parentId: 'status', id: 'bookmark_btn2', detail: { label: '取消',event: 'dialogClose' }},

  { type: 'dialog', id: 'bookmark', detail: { label: '我的书签', width: 600, modelName: 'bookmark',}},
  { type: 'table', parentId: 'bookmark', id: 'bookmark_table', detail: { label: '', pageSize:5, addable: false}},
  { type: 'tablecol', parentId: 'bookmark_table', id: 'bookmark_table_col1', detail: { label: '唯一标识',dataAttribute:'keyValue', event:'doQuery',inputMode: 'readonly'}},
  { type: 'tablecol', parentId: 'bookmark_table', id: 'bookmark_table_col2', detail: { label: '描述',dataAttribute:'desc',inputMode: 'readonly'}},
  { type: 'tablecol', parentId: 'bookmark_table', id: 'bookmark_table_col3', detail: { label: '创建时间',dataAttribute:'created_time',inputMode: 'readonly'}},
  { type: 'pushbutton', parentId: 'bookmark', id: 'bookmark_btn1', detail: { label: '确定',isDefault: true,event: 'dialogOk' }},
  { type: 'pushbutton', parentId: 'bookmark', id: 'bookmark_btn2', detail: { label: '取消',event: 'dialogClose' }},

  { type: 'dialog', id: 'viewQuery', detail: { label: '查看/管理查询', width: 700, modelName: 'filter', }},
  { type: 'table', parentId: 'viewQuery', id: 'viewQuery_table', detail: { label: '', pageSize:5, }},
  { type: 'tablecol', parentId: 'viewQuery_table', id: 'viewQuery_table_col1', detail: { label: '查询名称', dataAttribute:'clauseName', inputMode: 'readonly'}},
  { type: 'tablecol', parentId: 'viewQuery_table', id: 'viewQuery_table_col2', detail: { label: '描述', dataAttribute:'desc', inputMode: 'readonly'}},
  { type: 'tablecol', parentId: 'viewQuery_table', id: 'viewQuery_table_col3', detail: { label: '缺省', dataAttribute:'isDefault', dataType:'boolean'}},
  { type: 'tablecol', parentId: 'viewQuery_table', id: 'viewQuery_table_col4', detail: { label: '公用', dataAttribute:'isPublic', dataType:'boolean'}},
  { type: 'section', parentId: 'viewQuery_table', id: 'viewQuery_table_detail', detail: {}},
  { type: 'multilinetextbox', parentId: 'viewQuery_table_detail', id: 'viewQuery_table_detail_text1',
    detail: {label:'Where子句',dataAttribute: 'clause', inputMode:'required',rows:4}},
  { type: 'pushbutton', parentId: 'viewQuery', id: 'viewQuery_btn1', detail: { label: '确定',isDefault: true,event: 'dialogOk' }},
  { type: 'pushbutton', parentId: 'viewQuery', id: 'viewQuery_btn2', detail: { label: '取消',event: 'dialogClose' }},

  { type: 'dialog', id: 'saveQuery', detail: { label: '保存当前查询', width: 600}},
  { type: 'section', parentId: 'saveQuery', id: 'saveQuery_section', detail: {}},
  { type: 'multiparttextbox', parentId: 'saveQuery_section', id: 'saveQuery_section_text1',
    detail: {label:'查询名称',dataAttribute: 'clauseName', descDataAttribute: 'desc',inputMode:'required', }},
  { type: 'checkbox', parentId: 'saveQuery_section', id: 'saveQuery_section_cb2', detail: {label:'公用',dataAttribute: 'isPublic', }},
  { type: 'checkbox', parentId: 'saveQuery_section', id: 'saveQuery_section_cb3', detail: {label:'缺省',dataAttribute: 'isDefault', }},
  { type: 'pushbutton', parentId: 'saveQuery', id: 'saveQuery_btn1', detail: { label: '确定',isDefault: true,event: 'dialogOk' }},
  { type: 'pushbutton', parentId: 'saveQuery', id: 'saveQuery_btn2', detail: { label: '取消',event: 'dialogClose' }},

  { type: 'dialog', id: 'searchWhere', detail: { label: 'Where 子句', width: 600}},
  { type: 'section', parentId: 'searchWhere', id: 'searchWhere_section', detail: {}},
  { type: 'multilinetextbox', parentId: 'searchWhere_section', id: 'searchWhere_section_text1',
    detail: {label:'当前查询',dataAttribute: 'where', inputMode:'required',rows:4}},
  { type: 'pushbutton', parentId: 'searchWhere', id: 'searchWhere_btn1', detail: { label: '确定',isDefault: true,event: 'dialogOk' }},
  { type: 'pushbutton', parentId: 'searchWhere', id: 'searchWhere_btn2', detail: { label: '取消',event: 'dialogClose' }},

  { type: 'dialog', id: 'searchAttr', detail: { label: '属性搜索', width: 700, modelName: 'searchAttr',}},
  { type: 'table', parentId: 'searchAttr', id: 'searchAttr_table', detail: { label: '', pageSize:5,}},
  { type: 'tablecol', parentId: 'searchAttr_table', id: 'searchAttr_table_col1', detail: { label: '属性',dataAttribute:'attrID'}},
  { type: 'tablecol', parentId: 'searchAttr_table', id: 'searchAttr_table_col2', detail: { label: '数据类型',dataAttribute:'dataType'}},
  { type: 'tablecol', parentId: 'searchAttr_table', id: 'searchAttr_table_col3', detail: { label: '搜索值',dataAttribute:'specValue'}},
  { type: 'pushbutton', parentId: 'searchAttr', id: 'searchAttr_btn1', detail: { label: '确定',isDefault: true,event: 'dialogOk' }},
  { type: 'pushbutton', parentId: 'searchAttr', id: 'searchAttr_btn2', detail: { label: '取消',event: 'dialogClose' }},

  { type: 'dialog', id: 'completeWF', detail: { label: '完成工作流任务分配', width: 500, }},
  { type: 'section', parentId: 'completeWF', id: 'completeWF_section1', detail: {}},
  { type: 'paramvalue', parentId: 'completeWF_section1', id: 'completeWF_section1_text0', detail: {dataAttribute: 'linkTaskList.id'}},
  { type: 'textbox', parentId: 'completeWF_section1', id: 'completeWF_section1_text1',
    detail: {label:'任务描述',dataAttribute: 'linkTaskList.description', inputMode: 'readonly'}},
  { type: 'section', parentId: 'completeWF', id: 'completeWF_section2', detail: {}},
  { type: 'radiobuttongroup', parentId: 'completeWF_section2', id: 'completeWF_section2_rbg1',
    detail: {label:'操作',dataAttribute: 'linkTaskList.selectAction', inputMode:'required',keyAttribute: 'id', displayAttribute: 'name', listAttribute: 'linkTaskList.actionList', vertical: true}},
  { type: 'section', parentId: 'completeWF', id: 'completeWF_section3', detail: {}},
  { type: 'multilinetextbox', parentId: 'completeWF_section3', id: 'completeWF_section3_text1',
    detail: {label:'备注',dataAttribute: 'linkTaskList.comment',rows:4 }},
  { type: 'pushbutton', parentId: 'completeWF', id: 'completeWF_btn1', detail: { label: '确定',isDefault: true,event: 'completeWF' }},
  { type: 'pushbutton', parentId: 'completeWF', id: 'completeWF_btn2', detail: { label: '取消',event: 'dialogClose' }},

  { type: 'dialog', id: 'assignWF', detail: { label: '查看工作流任务分配', width: 700, }},
  { type: 'table', parentId: 'assignWF', id: 'assignWF_table', detail: { label: '', objName:'linkTaskList.candidatePersonList', pageSize:5, inputMode:'readonly'}},
  { type: 'tablecol', parentId: 'assignWF_table', id: 'assignWF_table_col1', detail: { label: '人员',dataAttribute:'personId'}},
  { type: 'tablecol', parentId: 'assignWF_table', id: 'assignWF_table_col2', detail: { label: '名称',dataAttribute:'personObj.displayName'}},
  { type: 'tablecol', parentId: 'assignWF_table', id: 'assignWF_table_col3', detail: { label: '任务描述',dataAttribute:'description'}},
  { type: 'tablecol', parentId: 'assignWF_table', id: 'assignWF_table_col4', detail: { label: '流程名称',dataAttribute:'processDefKey'}},
  { type: 'pushbutton', parentId: 'assignWF', id: 'assignWF_table_btn1', detail: { label: '确定',isDefault: true,event: 'dialogClose' }},
  { type: 'pushbutton', parentId: 'assignWF', id: 'assignWF_table_btn2', detail: { label: '查看工作流历史记录',event: 'historyWF', icon: 'history' }},
  { type: 'pushbutton', parentId: 'assignWF', id: 'assignWF_table_btn3', detail: { label: '查看工作流图',event: 'viewWF', icon: 'picture' }},

  { type: 'dialog', id: 'historyWF', detail: { label: '查看工作流历史记录', width: 700, }},
  { type: 'table', parentId: 'historyWF', id: 'historyWF_table', detail: { label: '', objName:'historyTaskList', pageSize:5, inputMode:'readonly'}},
  { type: 'tablecol', parentId: 'historyWF_table', id: 'historyWF_table_col4', detail: { label: '任务描述',dataAttribute:'description'}},
  { type: 'tablecol', parentId: 'historyWF_table', id: 'historyWF_table_col1', detail: { label: '审批人',dataAttribute:'approvePersonObj.displayName'}},
  { type: 'tablecol', parentId: 'historyWF_table', id: 'historyWF_table_col2', detail: { label: '审批日期',dataAttribute:'createTime'}},
  { type: 'tablecol', parentId: 'historyWF_table', id: 'historyWF_table_col3', detail: { label: '审批意见',dataAttribute:'comment'}},
  { type: 'pushbutton', parentId: 'historyWF', id: 'historyWF_table_btn1', detail: { label: '确定',isDefault: true,event: 'dialogClose' }},
  { type: 'pushbutton', parentId: 'historyWF', id: 'historyWF_table_btn2', detail: { label: '查看工作流图',event: 'viewWF', icon: 'picture' }},
  { type: 'pushbutton', parentId: 'historyWF', id: 'historyWF_table_btn3', detail: { label: '查看工作流任务分配',event: 'assignWF', icon: 'team' }},


  { type: 'dialog', id: 'viewWF', detail: { label: '查看工作流', width: 700, }},
  { type: 'section', parentId: 'viewWF', id: 'viewWF_section2', detail: {}},
  { type: 'custom', parentId: 'viewWF_section2', id: 'viewWF_section2_wfmap', detail: { fileName:'wfMap'} },
  { type: 'pushbutton', parentId: 'viewWF', id: 'assignWF_table_btn1', detail: { label: '确定',isDefault: true,event: 'dialogClose' }},
  { type: 'pushbutton', parentId: 'viewWF', id: 'assignWF_table_btn2', detail: { label: '查看工作流历史记录',event: 'historyWF', icon: 'history' }},
  { type: 'pushbutton', parentId: 'viewWF', id: 'assignWF_table_btn3', detail: { label: '查看工作流任务分配',event: 'assignWF', icon: 'team' }},
];
